### ISSUE TITLE
Exported Spritesheet animations aren't where they supposed to be

### ISSUE THREAD

**Issue by GreglyFNF** [UncertainProd/FNF-Spritesheet-XML-generator-Web#3]
A couple of times i used this website but i always run into a problem when trying to use them in the Psych Engine.  Some of the animations are bugged for some reason. even when the set animations are small.

**Comment by UncertainProd** [comment]
Can you give an example spritesheet where it didn't work?

**Comment by GreglyFNF** [comment]
[this one is fucked up.zip](https://github.com/UncertainProd/FNF-Spritesheet-XML-generator-Web/files/12042511/this.one.is.fucked.up.zip)
This is one of the spritesheets that got fucked

**Comment by UncertainProd** [comment]
Can you try it with the latest version and see if it's fixed?

**Comment by GreglyFNF** [comment]
alright ill see what i can do

**Comment by GreglyFNF** [comment]
IT WORKS.
