### ISSUE TITLE
[FEATURE REQUEST] Add back the `Clip to bounding box` option from the original app

### ISSUE THREAD

**Issue by doggogit** [UncertainProd/FNF-Spritesheet-XML-generator-Web#4]
As the title says, by default, the web version has the toggle to clip sprites to their bounding boxes enabled.

I, personally, dislike this, as when exporting individual PNGs can cause issues like the frame being abruptly cut or the image not maintaining the same position and being off-center.

Hopefully we get this option back so we can disable it.

**Comment by UncertainProd** [comment]
I've added it now in the latest version
