### ISSUE TITLE
Frames of the animation still move around despite having `Clip to bounding box` turned off.

### ISSUE THREAD

**Issue by doggogit** [UncertainProd/FNF-Spritesheet-XML-generator-Web#5]
As the title suggests, here is what's happening:

![schmoove](https://github.com/UncertainProd/FNF-Spritesheet-XML-generator-Web/assets/115869532/0b7a040c-be36-416b-b558-27dc5ebc651a)

**Comment by UncertainProd** [comment]
You can adjust the positioning of each frame by changing the frameX and frameY properties under `View > View XML structure`. That should help keep it in place

**Comment by doggogit** [comment]
The original application didn't have this issue, I never had to go inside of the XML structure to change frameX and frameY.

**Comment by UncertainProd** [comment]
Does it shake when used inside flixel as well?

**Comment by doggogit** [comment]
Yes, it does.

**Comment by UncertainProd** [comment]
Can you send the frames that you used?

**Comment by doggogit** [comment]
Sure thing.

[Here they are](https://github.com/UncertainProd/FNF-Spritesheet-XML-generator-Web/files/12053417/bar-down.zip).

**Comment by doggogit** [comment]
> Sure thing.
> 
> [Here they are](https://github.com/UncertainProd/FNF-Spritesheet-XML-generator-Web/files/12053417/bar-down.zip).

I did use Free Texture Packer to remake the spritesheet, as it has its own built-in image optimizer as soon as you export the sheet. Plus, it's known to be better in exporting than Adobe Animate.

**Comment by UncertainProd** [comment]
It seems to shake even on the original app when I tried it, are you using an older version?
(Edit: The animation preview on the app)
![Animation Preview 2023-07-15 01-19-25](https://github.com/UncertainProd/FNF-Spritesheet-XML-generator-Web/assets/83609901/86923617-7eec-4918-af1c-7fa40f59f69b)

**Comment by doggogit** [comment]
I used the latest version in both instances: Web and Desktop.

The reason I switched to Web is because the Desktop version, for whatever reason, throws out an error whenever I try to export all the frames as individual PNGs.

The error in question: 
![image](https://github.com/UncertainProd/FNF-Spritesheet-XML-generator-Web/assets/115869532/2cf46658-55e4-4220-a55b-839159e89698)

On the downside, this specific health bar doesn't have its own FLA counterpart. (there's two instances of the same bar, one for downscroll and one for upscroll (this is for downscroll))

**Comment by UncertainProd** [comment]
For now I guess the best way would be to adjust the frames using frameX and frameY and see if the generated XML and spritesheet work. The clip to bounding box option shouldn't affect positioning of the frames since the app adjusts frameX and frameY to make sure it looks the same visually regardless of whether the option is enabled or not

**Comment by doggogit** [comment]
> For now I guess the best way would be to adjust the frames using frameX and frameY and see if the generated XML and spritesheet work. The clip to bounding box option shouldn't affect positioning of the frames since the app adjusts frameX and frameY to make sure it looks the same visually regardless of whether the option is enabled or not

Alright, will do it this way. Was just weirded out because the original Desktop app never had this happen. Thank you for helping out.
